# Activity Recognition using Cell Phone Accelerometers
## by Jennifer R. Kwapisz, Gary M. Weiss, Samuel A. Moore
### Reproducing their results

---

## TODO  
[ ] Find a way to map back label (0-5) to nominal value

---

## Notes
The file had several '?' for missing values. I have changed that to '-99'. I should check how this affects the fit.

In [25]:
# Loading all the needed modules
import numpy as np
import arff
from sklearn.tree import DecisionTreeClassifier
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import linear_model
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_predict

In [16]:
root = '/Users/samiadrappeau/data_science/projets_perso/liberty_rider/'
dirin = 'WISDM/data_WISDM/'
fid = root + dirin + 'WISDM_ar_v1.1_transformed.arff'

In [17]:
dataset = arff.load(open(fid), 'rb')
data = np.array(dataset['data'])
data.shape

(5418, 46)

In [18]:
X = data[:,:45]
y = data[:,45]

In [19]:
print(np.unique(y))

[ 0.  1.  2.  3.  4.  5.]


In [20]:
target_names = ['Walking', 'Jogging', 'Upstairs', 'Downstairs', 'Sitting', 'Standing']

### Machine learning algorithms
#### Decision trees, Logistic regression and Multilayer Neural Network

In [21]:
# Declaring all three models used in the paper
clf = DecisionTreeClassifier(random_state=0)
logreg = linear_model.LogisticRegression(C=1e5)
MLPclf = MLPClassifier(random_state=1)

# Aggregating them
algo = [clf, logreg, MLPclf]

In [26]:
# 10-fold cross-validation
NBROUND = 10
kf = KFold(n_splits=NBROUND)
for  i, alg in enumerate(algo):
    estimator = alg
    pred = cross_val_predict(estimator, X, y, cv=10)
    print(classification_report(y, pred, target_names=target_names))
    print(confusion_matrix(y, pred))

             precision    recall  f1-score   support

    Walking       0.76      0.59      0.66      2081
    Jogging       0.88      0.90      0.89      1625
   Upstairs       0.28      0.35      0.31       632
 Downstairs       0.25      0.38      0.30       528
    Sitting       0.92      0.82      0.87       306
   Standing       0.76      0.90      0.82       246

avg / total       0.70      0.66      0.67      5418

[[1219  118  333  408    2    1]
 [  36 1466  100   22    1    0]
 [ 173   61  223  150    5   20]
 [ 181   19  124  198    3    3]
 [   1    2    4    0  251   48]
 [   3    2    3    4   12  222]]
             precision    recall  f1-score   support

    Walking       0.67      0.94      0.79      2081
    Jogging       0.89      0.93      0.91      1625
   Upstairs       0.46      0.15      0.22       632
 Downstairs       0.43      0.07      0.12       528
    Sitting       0.97      0.89      0.93       306
   Standing       0.90      0.80      0.85       246

a